### ISSUE TITLE
Update to new version of logstash

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/logsearch-boshrelease#111]
In order to update our logstash version, we want to update the logstash package and it's dependencies to the newest version of 7.x, or otherwise disable jndilookups

## Acceptance Criteria
* [ ] GIVEN the logstash package and it's dependencies are updated to the latest 7.x

--- 

## Security considerations
Unsure that updates do not interfere with our authentication workflow in our ELK stack

## Implementation sketch
* [ ] Package logstash version
* [ ] Package any logstash dependencies

**Comment by ccostino** [comment]
This issue is in response to Log4j, correct?  If so, I think we can close it because @bengerman13 was able to apply the fix Elastic.co had provided and rolled it out.

**Comment by ccostino** [comment]
Also calling out there is (or should be ) a separate issue as we still need to update the ELK stack in general.
