### ISSUE TITLE
Release download location / Request to publish releases

### ISSUE THREAD

**Issue by peterellisjones** [cloud-gov/logsearch-boshrelease#114]
Hi folks,

Are bosh releases publicly available for this project?

kind regards,

Pete

**Comment by bengerman13** [comment]
Hi @peterellisjones -
Our releases are not currently available publicly, and we don't have anything on the roadmap to make them.

You should be able to build from source, though

**Comment by peterellisjones** [comment]
>You should be able to build from source, though

Thanks @bengerman13,

The packages directory contains some vendored packages (such as openjdk 11 https://github.com/cloud-gov/logsearch-boshrelease/tree/develop/packages/openjdk-11) which are needed to build from source. I can't find the source for these packages in the repo -- are they published in a different repo?

**Comment by peterellisjones** [comment]
Update: I suspect these packages are from https://github.com/bosh-packages can you confirm?

**Comment by bengerman13** [comment]
openjdk11: https://github.com/bosh-packages/java-release
python3: https://github.com/cloud-gov/cg-python3-boshrelease

**Comment by peterellisjones** [comment]
Thanks!

**Comment by bengerman13** [comment]
No problem :)
