### ISSUE TITLE
Update Elasticsearch to more recent JDK (due 2022-02-20)

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/logsearch-boshrelease#124]
We should bump JDK and roll it out to clear scan findings.

## Security considerations
Enhancement / Std patching

## Implementation sketch

* See https://github.com/cloud-gov/logsearch-boshrelease/pull/107

**Comment by bengerman13** [comment]
Look at finding to see which JDKs need bumping

**Comment by bengerman13** [comment]
I believe this is done. Need to validate in Nessus tomorrow

**Comment by bengerman13** [comment]
So the vendoring is working, but we were still on the old version. 
Bumped correctly and deploying today. Will check nessus again tomorrow

**Comment by bengerman13** [comment]
these are scanning clean now 🎉
