### ISSUE TITLE
Update Elasticsearch to more recent JDK (due 2022-08-20) so - fix now? 

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/logsearch-boshrelease#134]
## Implementation

Notes about updating openjdk-11 release:

https://github.com/cloud-gov/internal-docs/blob/d9777abb8f8dfa306ae2b73f55ddd5296857d567/runbooks/building-bosh-releases.md

## Security considerations
Not revealing info that's not already OSS. Needed for compliance.

**Comment by markdboyd** [comment]
PR is up: https://github.com/cloud-gov/logsearch-boshrelease/pull/157

**Comment by markdboyd** [comment]
This change was merged and deployed to production, so closing this ticket
